import React from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { ExternalLink, Sparkles, X, ArrowRight, Play } from 'lucide-react';
import { VisualData } from '../types';
import { PUBLIC_SAMPLES } from '../constants/samples';

interface SampleGalleryProps {
  onCreateClick: (sample?: VisualData) => void;
}

export const SampleGallery: React.FC<SampleGalleryProps> = ({ onCreateClick }) => {
  const [selectedSample, setSelectedSample] = React.useState<VisualData | null>(null);

  return (
    <section className="mt-20">
      <div className="mb-10 text-center sm:text-left">
        <h2 className="text-3xl font-bold text-zinc-900 mb-3 tracking-tight">Featured Samples</h2>
        <p className="text-zinc-500 font-medium max-w-2xl">Explore real examples generated by VisualMate AI. These featured samples demonstrate the depth and clarity of our visual thinking engine.</p>
      </div>

      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-8">
        {PUBLIC_SAMPLES.map((sample) => (
          <motion.div
            key={sample.id}
            whileHover={{ y: -6 }}
            className="group bg-white rounded-[40px] border border-zinc-100 shadow-sm hover:shadow-2xl transition-all cursor-pointer overflow-hidden"
            onClick={() => setSelectedSample(sample)}
          >
            <div className="aspect-[4/3] relative overflow-hidden">
              <img 
                src={sample.imageUrl} 
                alt={sample.title}
                className="w-full h-full object-cover group-hover:scale-110 transition-transform duration-700"
                referrerPolicy="no-referrer"
              />
              <div className="absolute top-5 left-5">
                <span className="px-4 py-1.5 bg-emerald-600 text-[10px] font-bold text-white rounded-full uppercase tracking-widest shadow-xl border border-white/10">
                  Featured Sample
                </span>
              </div>
              <div className="absolute inset-0 bg-gradient-to-t from-black/60 via-transparent to-transparent opacity-0 group-hover:opacity-100 transition-opacity flex items-end p-8">
                <div className="w-12 h-12 bg-white rounded-2xl flex items-center justify-center shadow-2xl transform translate-y-4 group-hover:translate-y-0 transition-transform">
                  <ExternalLink className="w-5 h-5 text-zinc-900" />
                </div>
              </div>
            </div>
            <div className="p-8">
              <div className="flex items-center gap-3 mb-4">
                <span className="px-3 py-1 bg-emerald-50 text-emerald-700 text-[10px] font-bold rounded-full uppercase tracking-wider">
                  {sample.category}
                </span>
              </div>
              <h3 className="text-xl font-bold text-zinc-900 mb-3 group-hover:text-emerald-600 transition-colors tracking-tight">{sample.title}</h3>
              <p className="text-sm text-zinc-500 line-clamp-2 font-medium leading-relaxed mb-4">
                {sample.description}
              </p>
              <div className="flex items-center text-emerald-600 text-xs font-bold gap-1 opacity-0 group-hover:opacity-100 transition-opacity">
                View Details <ArrowRight className="w-3 h-3" />
              </div>
            </div>
          </motion.div>
        ))}
      </div>

      {/* Preview Modal */}
      <AnimatePresence>
        {selectedSample && (
          <div className="fixed inset-0 z-[150] flex items-center justify-center p-4 sm:p-8 bg-zinc-950/80 backdrop-blur-xl">
            <motion.div
              initial={{ opacity: 0, scale: 0.9, y: 40 }}
              animate={{ opacity: 1, scale: 1, y: 0 }}
              exit={{ opacity: 0, scale: 0.9, y: 40 }}
              className="bg-white rounded-[48px] shadow-2xl max-w-6xl w-full max-h-[90vh] overflow-hidden flex flex-col lg:flex-row border border-white/20"
            >
              {/* Image Side */}
              <div className="lg:w-3/5 bg-zinc-50 relative flex items-center justify-center p-8 lg:p-12">
                <div className="w-full h-full rounded-[32px] overflow-hidden shadow-2xl bg-white border border-zinc-100">
                  <img 
                    src={selectedSample.imageUrl} 
                    alt={selectedSample.title}
                    className="w-full h-full object-contain"
                    referrerPolicy="no-referrer"
                  />
                </div>
                <button 
                  onClick={() => setSelectedSample(null)}
                  className="absolute top-8 right-8 p-3 bg-zinc-900/10 hover:bg-zinc-900/20 text-zinc-900 rounded-full backdrop-blur-md transition-all lg:hidden"
                >
                  <X className="w-5 h-5" />
                </button>
              </div>

              {/* Content Side */}
              <div className="lg:w-2/5 p-8 lg:p-12 overflow-y-auto flex flex-col bg-white">
                <div className="flex items-center justify-between mb-10">
                  <div className="flex items-center gap-4">
                    <div className="w-12 h-12 bg-emerald-50 text-emerald-600 rounded-2xl flex items-center justify-center shadow-sm">
                      <Sparkles className="w-6 h-6" />
                    </div>
                    <div>
                      <span className="text-[10px] font-bold text-zinc-400 uppercase tracking-widest block mb-0.5">Featured Sample</span>
                      <h3 className="font-bold text-2xl text-zinc-900 tracking-tight">{selectedSample.title}</h3>
                    </div>
                  </div>
                  <button 
                    onClick={() => setSelectedSample(null)}
                    className="p-2 hover:bg-zinc-100 rounded-full transition-colors hidden lg:block"
                  >
                    <X className="w-5 h-5 text-zinc-400" />
                  </button>
                </div>

                <div className="space-y-10 flex-1">
                  <div>
                    <h4 className="text-[10px] font-bold text-zinc-400 uppercase tracking-widest mb-4 flex items-center gap-2">
                      <Play className="w-3 h-3 fill-current" /> Example Prompt
                    </h4>
                    <div className="p-6 bg-zinc-50 rounded-3xl border border-zinc-100 italic text-sm text-zinc-600 leading-relaxed font-medium relative group">
                      "{selectedSample.imagePrompt}"
                      <div className="absolute -top-2 -right-2 w-8 h-8 bg-white rounded-xl border border-zinc-100 flex items-center justify-center shadow-sm opacity-0 group-hover:opacity-100 transition-opacity">
                        <Sparkles className="w-4 h-4 text-emerald-500" />
                      </div>
                    </div>
                  </div>

                  <div>
                    <h4 className="text-[10px] font-bold text-zinc-400 uppercase tracking-widest mb-4">Visual Breakdown</h4>
                    <div className="grid grid-cols-2 gap-3">
                      {selectedSample.nodes.map((node, i) => (
                        <div key={i} className="p-3 bg-zinc-50 rounded-2xl border border-zinc-100 flex items-center gap-3">
                          <div className="w-2 h-2 bg-emerald-500 rounded-full shrink-0" />
                          <div className="min-w-0">
                            <p className="text-xs font-bold text-zinc-900 truncate">{node.label}</p>
                            <p className="text-[10px] text-zinc-400 uppercase font-bold tracking-tighter">{node.type}</p>
                          </div>
                        </div>
                      ))}
                    </div>
                  </div>

                  <div className="p-6 bg-emerald-50 rounded-3xl border border-emerald-100 relative overflow-hidden">
                    <div className="absolute top-0 right-0 w-24 h-24 bg-emerald-100/50 rounded-full -mr-12 -mt-12 blur-2xl" />
                    <p className="text-xs text-emerald-800 font-medium leading-relaxed italic relative z-10">
                      "{selectedSample.commentary}"
                    </p>
                  </div>
                </div>

                <div className="mt-12">
                  <button 
                    onClick={() => {
                      onCreateClick(selectedSample);
                      setSelectedSample(null);
                    }}
                    className="w-full py-5 bg-zinc-900 text-white font-bold rounded-[24px] hover:bg-zinc-800 transition-all shadow-2xl flex items-center justify-center gap-3 group"
                  >
                    <Sparkles className="w-5 h-5 text-emerald-400" />
                    Create Similar Visual
                    <ArrowRight className="w-5 h-5 group-hover:translate-x-1 transition-transform" />
                  </button>
                </div>
              </div>
            </motion.div>
          </div>
        )}
      </AnimatePresence>
    </section>
  );
};
